### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AleksanderBondar** [graphql-editor/gei-users#30]
- [x] brak zapraszania samego siebie
- [x] w delete team team id a nie team name
- [x] dodać wysyłanie linku na email przy zaproszeniu
- [x] issue od elwisa --> forgot password / change password zamiast changePassword
- [ ] dodać jakiś sposób na rejestracje przez social + token z teamu
- [x] rejestracja na GitHubie chyba wymaga e-maila (mogę się mylić) -> https://api.github.com/user/emails -> scope: 'user:email'
